import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faArrowRight,
  faBiohazard,
  faCamera,
  faCar,
  faCheck,
  faCheckSquare,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faCoffinCross,
  faDirections,
  faEnvelope,
  faExclamationSquare,
  faFileCsv,
  faFileExcel,
  faFileInvoice,
  faFilePdf,
  faFileWord,
  faFilter,
  faFlower,
  faHourglass,
  faImage,
  faInfo,
  faMap,
  faMapMarker,
  faPaperclip,
  faPen,
  faPhone,
  faPlus,
  faStream,
  faTimes,
  faUser,
  faUsers,
  faUserTag,
  faCogs,
  faBuilding,
  faPlaceOfWorship,
  faTombstoneAlt,
  faWalker,
  faHospital,
} from "@fortawesome/pro-light-svg-icons";

library.add(
  faArrowRight,
  faBiohazard,
  faCamera,
  faCar,
  faCheck,
  faCheckSquare,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faCoffinCross,
  faDirections,
  faEnvelope,
  faExclamationSquare,
  faFileCsv,
  faFileExcel,
  faFileInvoice,
  faFilePdf,
  faFileWord,
  faFilter,
  faFlower,
  faHourglass,
  faImage,
  faInfo,
  faMap,
  faMapMarker,
  faPaperclip,
  faPen,
  faPhone,
  faPlus,
  faStream,
  faTimes,
  faUser,
  faUsers,
  faUserTag,
  faCogs,
  faBuilding,
  faPlaceOfWorship,
  faTombstoneAlt,
  faWalker,
  faHospital,
);

export default (app) => {
  // eslint-disable-next-line vue/component-definition-name-casing
  app.component("font-awesome-icon", FontAwesomeIcon);
};
